CREATE TABLE PLAYERS_STATS_F (

  Player_id VARCHAR(9) NOT NULL,
  Year INT NOT NULL,
  Pos VARCHAR(10) NOT NULL,
  Age INT(2) NOT NULL,
  Team VARCHAR(5) NOT NULL,
  GP INT NOT NULL,
  MP INT NOT NULL,
  FGM FLOAT NOT NULL,
  FG_PER FLOAT NOT NULL,
  3PM FLOAT NOT NULL,
  3PA FLOAT NOT NULL,
  3P_PER FLOAT NOT NULL,
  eFG_PER FLOAT NOT NULL,
  FT_PER FLOAT NOT NULL,
  TRB FLOAT NOT NULL,
  STL FLOAT NOT NULL,
  BLK FLOAT NOT NULL,
  AST FLOAT NOT NULL,
  TO FLOAT NOT NULL,
  ATO FLOAT NOT NULL
);

CREATE TABLE PLAYERS_D (
  Player_id VARCHAR(9) NOT NULL,
  Player_name VARCHAR(55) NOT NULL
);

CREATE TABLE PLAYERS_SALARY_F (
  Player_id VARCHAR(9) NOT NULL,
  Year INT NOT NULL,
  Salary FLOAT NOT NULL
);

CREATE TABLE FINAL_DATA (
  Player_id VARCHAR(9) NOT NULL,
  Player_name VARCHAR(55) NOT NULL,
  Year INT NOT NULL,
  Pos VARCHAR(10) NOT NULL,
  Age INT(2) NOT NULL,
  Team VARCHAR(5) NOT NULL,
  GP INT NOT NULL,
  MP INT NOT NULL,
  FGM FLOAT NOT NULL,
  FG_PER FLOAT NOT NULL,
  3PM FLOAT NOT NULL,
  3PA FLOAT NOT NULL,
  3P_PER FLOAT NOT NULL,
  eFG_PER FLOAT NOT NULL,
  FT_PER FLOAT NOT NULL,
  TRB FLOAT NOT NULL,
  STL FLOAT NOT NULL,
  BLK FLOAT NOT NULL,
  AST FLOAT NOT NULL,
  TO FLOAT NOT NULL,
  ATO FLOAT NOT NULL
);
